language: rust

# only cache cargo subcommand binaries and .so libs
# the build artifacts take a lot of space and are slower to
# cache than to actually rebuild anyway...
# We need to cache the whole .cargo directory to keep the
# .crates.toml file.
cache:
  directories:
    - /home/travis/install
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

dist: trusty

sudo: false

rust:
  - nightly
#  - beta
#  - latest

matrix:
  include:
    - name: rustfmt --check
      rust: nightly
      env: BUILD_FMT=1
    - name: clippy
      rust: nightly
      env: CLIPPY=1
    - name: cargo test
      rust: nightly
      env: TEST=1
      os:
        - linux
        - osx
        - windows

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - mkdir $(pwd)/socket
  - export XDG_RUNTIME_DIR="$(pwd)/socket"
  - cargo fetch
  - |
    rustup update
    rustup component add rustfmt-preview
    rustup component list
    if [ -n "$CLIPPY" ]; then
      rustup component add clippy-preview
    fi
os:
  - linux
script:
  - |
    if [ -n "$BUILD_FMT" ]; then
      cargo fmt --all -- --check
      rustfmt --check src/*.rs
    elif [ -n "$CLIPPY" ]; then
      cargo clippy --all -- -D warnings \
        -A clippy::deprecated_cfg_attr \
        -A clippy::for_loop_over_option
    elif [ -n "$TEST" ]; then
      cargo test --all --verbose
    else
      cargo test --all --features "$FEATURES"
    fi
